### PR TITLE
Installation

### PR DESCRIPTION
**Pull request by kellinpelrine**
Added environment.yaml containing Conda environment with necessary packages, to be used with "conda env create -f environment.yaml"

Added install.py file, to be run once initially to download necessary nltk files.

Edited readability.py: easy_word_set import was throwing error; corrected following https://stackoverflow.com/questions/62018759/importerror-cannot-import-name-easy-word-set-from-textstat-textstat

### CODE REVIEW

**Comment by zhouhanc** [comment]
Hi @kellinpelrine , this looks great! thanks so much for putting the dependencies together.

I just have one comment: can you remove (or add to .gitignore) `.pyc` files and `__pycache__/` subfolders you committed? After that I will merge the PR.

**Comment by kellinpelrine** [comment]
Sure, I've done that now. There were 3 .pyc files from your original repo that I've left as I wasn't sure if you wanted me to remove those too; I can take out the folder entirely if you want that.

**Comment by zhouhanc** [comment]
Yes you can take out the `__pycache__` folder entirely. I should not have pushed this folder in the first place.

After you remove the folder, can you please rebase your commits into one? `git rebase -i` and choose `squash` for previous commits should work.

**Comment by kellinpelrine** [comment]
OK, I've removed that folder and added a .gitignore to avoid it in the future.

I was having a bit of trouble squashing so I just made another branch/PR. Incidentally I think there may be an option to squash commits when you merge them (dropdown on the merge button here). But not sure if that would have worked in this case.

**Pull request closed without merging**
